version: '3.8'

services:
  botlandia-frontend:
    build:
      context: ./frontend  # Caminho para o diretório do seu aplicativo React
      dockerfile: Dockerfile    # Nome do Dockerfile (caso seja diferente, ajuste aqui)
    container_name: botlandia-front
    env_file:
      - env.docker-compose
    ports:
      - "8080:80"  # Mapeia a porta 80 do host para a porta 80 do container (ajuste se necessário)
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - botlandia-backend

  botlandia-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: botlandia-backend
    ports:
      - "3001:3001"
    env_file:
      - env.docker-compose
    depends_on:
      - botlandia-rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./environment/botlandia-backend:/app/botlandia/botlandia-backend/
      - ./environment/tmp:/botlandia/tmp
      - ./environment/public:/botlandia/public
      - ./environment/download:/botlandia/download
  botlandia-api-whatsapp:
    build:
      context: ./api-whatsapp
      dockerfile: Dockerfile
    container_name: botlandia-api-whatsapp
    ports:
      - "3002:3002"
    env_file:
      - env.docker-compose
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - botlandia-rabbitmq
    volumes:
      - ./environment/botlandia-api-whatsapp:/app/wwebjs_auth
      - ./environment/tmp:/botlandia/tmp
      - ./environment/public:/botlandia/public
      - ./environment/download:/botlandia/download

  botlandia-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: botlandia-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: botlandia
      MONGO_INITDB_ROOT_PASSWORD: botlandia
    volumes:
      - ./environment/botlandia-mongo:/data/db  # Mapeia para diretório local
    ports:
      - "27017:27017"
    networks:
      - app-network

  botlandia-rabbitmq:
    image: rabbitmq:management
    container_name: botlandia-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: botlandia
      RABBITMQ_DEFAULT_PASS: botlandia
    ports:
      - "5672:5672"      # Porta padrão do RabbitMQ
      - "15672:15672"    # Porta do console de gerenciamento
    volumes:
      - ./environment/botlandia-rabbitmq:/var/lib/rabbitmq  # Mapeia para diretório local
    networks:
      - app-network

  botlandia-ollama:
    image: ollama/ollama
    container_name: botlandia-ollama
    tty: true
    pull_policy: always
    networks:
      - app-network
    restart: unless-stopped
    entrypoint: [ "/bin/sh", "/botlandia-ollama/run_ollama.sh" ]
    volumes:
      - ./environment/botlandia-ollama:/botlandia-ollama
      - ./environment/botlandia-ollama/root:/root

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  back-data:
